name: setup-terminal-colors
description: >-
  Persist colors and other tput font controls
  to the terminal via environment variables

branding:
  color: purple
  icon: feather

inputs: {}

outputs:
  RESET:
    description: Reset all text styles
    value: ${{ steps.run.outputs.RESET }}
  BOLD:
    description: Make the text bold
    value: ${{ steps.run.outputs.BOLD }}

runs:
  using: composite
  steps:
    -
      id: run
      shell: bash
      run: |
        # Persist color commands to the runner's environment
        
        ${{ github.action_path }}/scripts/setup-env.sh
