name: pr

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        id: colors
        uses: ./.
      -
        name: Print some colored content
        env:
          RESET: ${{ steps.colors.outputs.RESET }}
          BOLD: ${{ steps.colors.outputs.BOLD }}
        run: |
          echo -e "${BOLD}Bold text${RESET}"
          echo -e "${GREEN}GREEN text${RESET}"
          echo -e "${RED}RED text${RESET}"
